version: '3'

services:
  web:
    container_name: alumni
    restart: always
    build: 
      context: .
      dockerfile: deploy/Dockerfile
    volumes:
      - .:/app
      - ./db:/var/lib/mysql
    ports:
      - "8081:80"
    ulimits:
        nproc: 65535
        nofile:
            soft: 50000
            hard: 100000
