version: '3'

services:
  web:
    container_name: alumni
    restart: always
    build: 
      context: .
      dockerfile: deploy/Dockerfile
    volumes:
      - .:/app
      - ./db:/var/lib/mysql
    # uid/gid lists from host
      - /etc/passwd:/etc/passwd.src:ro
      - /etc/group:/etc/group.src:ro
    environment:
      - host_users=www-data,mysql
      - host_groups=www-data,mysql,staff
    ports:
      - "8081:80"
    ulimits:
        nproc: 65535
        nofile:
            soft: 50000
            hard: 100000
